
apiVersion: v1
kind: Service
metadata:
  name: studentsurvey-service
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-studentsurvey-deployment
spec:
  type: NodePort
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-studentsurvey-deployment
  ports:
  - nodePort: 31416
    port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
